### ISSUE TITLE
Can't install the dependencies for this module / node LTS

### ISSUE THREAD

**Issue by jonattfin** [thinhvo0108/react-paypal-express-checkout#10]

**Comment by jonattfin** [comment]
> react-paypal-express-checkout@1.0.3 prepublish C:\projects\github\paypal\react-paypal-express-checkout
> babel --plugins 'transform-es2015-modules-umd' src --ignore __tests__ --out-dir ./dist

ReferenceError: Unknown plugin "'transform-es2015-modules-umd'" specified in "base" at 0, attempted to resolve relative to "src"
    at C:\projects\github\paypal\react-paypal-express-checkout\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (C:\projects\github\paypal\react-paypal-express-checkout\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\projects\github\paypal\react-paypal-express-checkout\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\projects\github\paypal\react-paypal-express-checkout\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\projects\github\paypal\react-paypal-express-checkout\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\projects\github\paypal\react-paypal-express-checkout\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\projects\github\paypal\react-paypal-express-checkout\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\projects\github\paypal\react-paypal-express-checkout\node_modules\babel-cli\lib\babel\util.js:50:22)
    at Object.compile (C:\projects\github\paypal\react-paypal-express-checkout\node_modules\babel-cli\lib\babel\util.js:59:12)

**Comment by thinhvo0108** [comment]
@jonattfin Have you tried install the "transform-es2015-modules-umd" library manually? On Windows environment, we may have problem installing libraries, I think

**Comment by thinhvo0108** [comment]
I have just updated the latest version (@1.0.4)
Could you please try using it? Thanks!

**Comment by thinhvo0108** [comment]
Close this issue, this was related to specific development environment setup on Windows, was not related to this component, thanks!
